### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::5000

### ISSUE THREAD

**Issue by Adylitto** [Adylitto/openai#1]
npm run server

> codex-server@0.0.0 server
> nodemon server

[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at Function.listen (/Users/adylitto/CODE/openai/server/node_modules/express/lib/application.js:635:24)
    at file:///Users/adylitto/CODE/openai/server/server.js:48:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5000
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ail3ngrimaldi** [comment]
Im facing the same issue, were you able to solve it?

**Comment by Adylitto** [comment]
token limitation i guess
